name: Build Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          lfs: true

      - name: Extract Boost headers
        run: |
          cd external\KenshiLib_Examples_deps\boost_1_60_0
          tar -xf boost.zip

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build
        run: >
          msbuild src\Dust.vcxproj
          /p:Configuration=Release
          /p:Platform=x64
